title: Klára Pitlachová
email: karelsuchomel@windowslive.com
description: >-
  Doprovázení, poradenství, terapie - pomoc při překonávání nejasného úseku vaší životní cesty.
keywords: Psycholožka, psycholog, soukromá psychologická praxe, psycholog Brno, doprovázení, poradenství, terapie
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://klarapitlachova.cz" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache

prose:
  siteurl: 'https://klarapitlachova.cz'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'assets/files/'
  ignore:
    - _config.yml
    - Gemfile.lock
    - Gemfile
    - CNAME
    - 404.html
    - .gitignore
    - /assets
    - /_site
    - /_layouts
    - /_includes
    - /_sass
    - /_posts
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"

    index.md:
      - name: "layout"
        field:
          element: "hidden"
          value: "front-page"
      - name: "title"
        field:
          element: "text"
          label: "Nadpis"
          value: "Hlavní strana"
      - name: "basicCardName"
        field:
          element: "text"
          label: "Vizitka - Jméno"
      - name: "basicCardExpertise"
        field:
          element: "textarea"
          label: "Vizitka - text"
      - name: "basicCardTelephone"
        field:
          element: "text"
          label: "Vizitka - telefon"
      - name: "firstSegmentHeadilne"
        field:
          element: "text"
          label: "První blok - nadpis"
      - name: "firstSegmentTextColumnLeft"
        field:
          element: "textarea"
          label: "První blok - sloupec nalevo"
      - name: "firstSegmentTextColumnRight"
        field:
          element: "textarea"
          label: "První blok - sloupec napravo"
      - name: "qutoSegmentText"
        field:
          element: "textarea"
          label: "Citát - text" 
      - name: "secondSegmentHeadilne"
        field:
          element: "text"
          label: "Durhý blok - nadpis"
      - name: "secondSegmentBody"
        field:
          element: "textarea"
          label: "Druhý blok - text"
      - name: "thirdSegmentHeadilne"
        field:
          element: "text"
          label: "Třetí blok - nadpis"
      - name: "thirdSegmentBody"
        field:
          element: "textarea"
          label: "Třetí blok - text"
      - name: "fourthSegmentHeadilne"
        field:
          element: "text"
          label: "Čtvrtý blok - nadpis"
      - name: "fourthSegmentBody"
        field:
          element: "textarea"
          label: "Čtvrtý blok - text"
      - name: "fifthSegmentHeadilne"
        field:
          element: "text"
          label: "Pátý blok - nadpis"
      - name: "fifthSegmentBody"
        field:
          element: "textarea"
          label: "Pátý blok - text"

    jak-pracuji.md:
      - name: "layout"
        field:
          element: "hidden"
          value: "how-i-work-page"
      - name: "title"
        field:
          element: "text"
          label: "Nadpis"
      - name: "FirstHeadilne"
        field:
          element: "text"
          label: "První blok - nadpis"
      - name: "FirstTextBoxLeft"
        field:
          element: "textarea"
          label: "První blok - sloupec nalevo"
      - name: "FirstTextBoxRight"
        field:
          element: "textarea"
          label: "První blok - sloupec napravo"
      - name: 'quotationBlock'
        field:
          element: "textarea"
          label: "Citace - text"      
      - name: "SecondHeadilne"
        field:
          element: "text"
          label: "Druhý blok - nadpis"
      - name: "SecondTextBoxLeft"
        field:
          element: "textarea"
          label: "Druhý blok - sloupec nalevo"
      - name: "SecondTextBoxRight"
        field:
          element: "textarea"
          label: "Druhý blok - sloupec napravo"

    vzdelani.md:
      - name: "layout"
        field:
          element: "hidden"
          value: "education-page"
      - name: "title"
        field:
          element: "text"
          label: "Nadpis"
      - name: "educationListHeadline"
        field:
          element: "text"
          label: "Levý blok - nadpis"
      - name: "educationListBody"
        field:
          element: "textarea"
          label: "Levý blok - seznam"
      - name: "experienceListHeadline"
        field:
          element: "text"
          label: "Pravý blok - nadpis"
      - name: "experienceListBody"
        field:
          element: "textarea"
          label: "Pravý blok - seznam"